name: Web Development App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-api:

    runs-on: ubuntu-latest
    
#     defaults:
#       run:
#         working-directory: Week8/webapi

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./Week8/webapi
      run: dotnet restore
    - name: Build
      working-directory: ./Week8/webapi
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Week8/webapi.tests
      run: dotnet test --no-build --verbosity normal
