name: Web Development App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-api:

    runs-on: ubuntu-latest

    steps:
    
    - name: Check out repo
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore API dependencies
      working-directory: ./Week8/webapi
      run: dotnet restore
      
    - name: Build API
      working-directory: ./Week8/webapi
      run: dotnet build --no-restore
      
    - name: Run API Unit Tests
      working-directory: ./Week8/webapi.tests
      run: dotnet test --verbosity minimal
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        context: ./Week8/webapi
        push: true
        tags: oitgaden/webapi:latest
